sudo: true
  
language:
  - cpp

before_install:
  - sudo apt-get install libsdl1.2-dev libsdl-mixer1.2-dev

script:
  - mkdir build
  - cd build
  - cmake ../trunk -DLOAD_RESOURCES_FROM_FILES:BOOL=ON
  - make

notifications:
  email: false
